FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./apps/api ./apps/api
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json

RUN npm install 


EXPOSE 8080

CMD ["pnpm", "run", "start:api"]